d2BC <-
function(descr_collect, hh){
  ## Function for computation of d2BC given a matrix with descriptive statistics in Roos et al. (2020)
  ## input: matrix with descritive statistics generated by the descr_extract function
  ## output: a vector with the second derivative of BC
  nr<-nrow(descr_collect)
  d2BC<-rep(NA, nr)
  # Computation of the second derivative d2BC
  for (i in 1:nr){
    d2BC[i]<-(BC_normal_total(m1=descr_collect[i,"m_u"], sd1=descr_collect[i,"sd_u"], m0=descr_collect[i,"m_0"], sd0=descr_collect[i,"sd_0"])-2+BC_normal_total(m1=descr_collect[i,"m_l"], sd1=descr_collect[i,"sd_l"], m0=descr_collect[i,"m_0"], sd0=descr_collect[i,"sd_0"]))/hh^2
  }
  return(d2BC)
}
